const mongoose = require('mongoose');
require('dotenv').config();
const Product = require('./models/Product');

// Data from Imerbela Reseller Price List 2026-2027
const products = [
  // 1. Neem Kernel Seeds Shampoo 300ml
  {
    handle: 'shampoo-300ml-3nos',
    title: 'Neem Kernel Seeds Shampoo',
    subtitle: '300ml X 03 Nos',
    benefit: 'Scalp balance pack of 3',
    price: 894, // Selling Amt
    mrpPerUnit: 1590, // MRP for 3
    imageUrl: '/shampoo-150ml.png',
    category: 'shampoo',
    tags: ['300ml', '3nos', 'bundle'],
    description: 'A professional-grade scalp balancing cleanser in a wholesale pack of 3. Formulated with high-purity Neem Seed Kernel extract.',
    howToUse: ['Apply to wet hair.', 'Massage and rinse.', 'Repeat if needed.'],
    ingredients: [{ name: 'Neem Seed Kernel', benefit: 'Anti-bacterial' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'shampoo-300ml-6nos',
    title: 'Neem Kernel Seeds Shampoo',
    subtitle: '300ml X 06 Nos',
    benefit: 'Scalp balance pack of 6',
    price: 1734,
    mrpPerUnit: 3180,
    imageUrl: '/shampoo-150ml.png',
    category: 'shampoo',
    tags: ['300ml', '6nos', 'bundle'],
    description: 'A professional-grade scalp balancing cleanser in a wholesale pack of 6. Ideal for medium-sized retail shelf space.',
    howToUse: ['Apply to wet hair.', 'Massage and rinse.', 'Repeat if needed.'],
    ingredients: [{ name: 'Neem Seed Kernel', benefit: 'Anti-bacterial' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'shampoo-300ml-12nos',
    title: 'Neem Kernel Seeds Shampoo',
    subtitle: '300ml X 12 Nos',
    benefit: 'Scalp balance pack of 12',
    price: 3372,
    mrpPerUnit: 6360,
    imageUrl: '/shampoo-150ml.png',
    category: 'shampoo',
    tags: ['300ml', '12nos', 'bundle'],
    description: 'A professional-grade scalp balancing cleanser in a bulk wholesale pack of 12. Maximum profit margin for premium partners.',
    howToUse: ['Apply to wet hair.', 'Massage and rinse.', 'Repeat if needed.'],
    ingredients: [{ name: 'Neem Seed Kernel', benefit: 'Anti-bacterial' }],
    moq: 1,
    isActive: true,
  },

  // 2. Neem Kernel Seeds Shampoo 150ml
  {
    handle: 'shampoo-150ml-3nos',
    title: 'Neem Kernel Seeds Shampoo',
    subtitle: '150ml X 03 Nos',
    benefit: 'Compact scalp cleanser pack of 3',
    price: 474,
    mrpPerUnit: 840,
    imageUrl: '/shampoo-150ml.png',
    category: 'shampoo',
    tags: ['150ml', '3nos', 'bundle'],
    description: 'Travel-friendly size in a wholesale pack of 3.',
    howToUse: ['Apply to wet hair.', 'Massage and rinse.'],
    ingredients: [{ name: 'Neem Seed Kernel', benefit: 'Anti-bacterial' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'shampoo-150ml-6nos',
    title: 'Neem Kernel Seeds Shampoo',
    subtitle: '150ml X 06 Nos',
    benefit: 'Compact scalp cleanser pack of 6',
    price: 918,
    mrpPerUnit: 1680,
    imageUrl: '/shampoo-150ml.png',
    category: 'shampoo',
    tags: ['150ml', '6nos', 'bundle'],
    description: 'Travel-friendly size in a wholesale pack of 6.',
    howToUse: ['Apply to wet hair.', 'Massage and rinse.'],
    ingredients: [{ name: 'Neem Seed Kernel', benefit: 'Anti-bacterial' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'shampoo-150ml-12nos',
    title: 'Neem Kernel Seeds Shampoo',
    subtitle: '150ml X 12 Nos',
    benefit: 'Compact scalp cleanser pack of 12',
    price: 1788,
    mrpPerUnit: 3360,
    imageUrl: '/shampoo-150ml.png',
    category: 'shampoo',
    tags: ['150ml', '12nos', 'bundle'],
    description: 'Travel-friendly size in a wholesale pack of 12.',
    howToUse: ['Apply to wet hair.', 'Massage and rinse.'],
    ingredients: [{ name: 'Neem Seed Kernel', benefit: 'Anti-bacterial' }],
    moq: 1,
    isActive: true,
  },

  // 3. Neem Kernel Seeds Conditioner 300ml
  {
    handle: 'conditioner-300ml-3nos',
    title: 'Neem Kernel Seeds Conditioner',
    subtitle: '300ml X 03 Nos',
    benefit: 'Hydration therapy pack of 3',
    price: 735,
    mrpPerUnit: 1305,
    imageUrl: '/conditioner-150ml.png',
    category: 'conditioner',
    tags: ['300ml', '3nos', 'bundle'],
    description: 'Intensive hydration therapy in a wholesale pack of 3.',
    howToUse: ['Apply to hair lengths.', 'Leave for 2 min.', 'Rinse.'],
    ingredients: [{ name: 'Neem Oil', benefit: 'Conditioning' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'conditioner-300ml-6nos',
    title: 'Neem Kernel Seeds Conditioner',
    subtitle: '300ml X 06 Nos',
    benefit: 'Hydration therapy pack of 6',
    price: 1428,
    mrpPerUnit: 2610,
    imageUrl: '/conditioner-150ml.png',
    category: 'conditioner',
    tags: ['300ml', '6nos', 'bundle'],
    description: 'Intensive hydration therapy in a wholesale pack of 6.',
    howToUse: ['Apply to hair lengths.', 'Leave for 2 min.', 'Rinse.'],
    ingredients: [{ name: 'Neem Oil', benefit: 'Conditioning' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'conditioner-300ml-12nos',
    title: 'Neem Kernel Seeds Conditioner',
    subtitle: '300ml X 12 Nos',
    benefit: 'Hydration therapy pack of 12',
    price: 2772,
    mrpPerUnit: 5220,
    imageUrl: '/conditioner-150ml.png',
    category: 'conditioner',
    tags: ['300ml', '12nos', 'bundle'],
    description: 'Intensive hydration therapy in a wholesale pack of 12.',
    howToUse: ['Apply to hair lengths.', 'Leave for 2 min.', 'Rinse.'],
    ingredients: [{ name: 'Neem Oil', benefit: 'Conditioning' }],
    moq: 1,
    isActive: true,
  },

  // 4. Neem Kernel Seeds Conditioner 150ml
  {
    handle: 'conditioner-150ml-3nos',
    title: 'Neem Kernel Seeds Conditioner',
    subtitle: '150ml X 03 Nos',
    benefit: 'Compact hydration therapy pack of 3',
    price: 387,
    mrpPerUnit: 690,
    imageUrl: '/conditioner-150ml.png',
    category: 'conditioner',
    tags: ['150ml', '3nos', 'bundle'],
    description: 'Travel size hydration therapy in a pack of 3.',
    howToUse: ['Apply to hair lengths.', 'Rinse.'],
    ingredients: [{ name: 'Neem Oil', benefit: 'Conditioning' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'conditioner-150ml-6nos',
    title: 'Neem Kernel Seeds Conditioner',
    subtitle: '150ml X 06 Nos',
    benefit: 'Compact hydration therapy pack of 6',
    price: 756,
    mrpPerUnit: 1380,
    imageUrl: '/conditioner-150ml.png',
    category: 'conditioner',
    tags: ['150ml', '6nos', 'bundle'],
    description: 'Travel size hydration therapy in a pack of 6.',
    howToUse: ['Apply to hair lengths.', 'Rinse.'],
    ingredients: [{ name: 'Neem Oil', benefit: 'Conditioning' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'conditioner-150ml-12nos',
    title: 'Neem Kernel Seeds Conditioner',
    subtitle: '150ml X 12 Nos',
    benefit: 'Compact hydration therapy pack of 12',
    price: 1464,
    mrpPerUnit: 2760,
    imageUrl: '/conditioner-150ml.png',
    category: 'conditioner',
    tags: ['150ml', '12nos', 'bundle'],
    description: 'Travel size hydration therapy in a pack of 12.',
    howToUse: ['Apply to hair lengths.', 'Rinse.'],
    ingredients: [{ name: 'Neem Oil', benefit: 'Conditioning' }],
    moq: 1,
    isActive: true,
  },

  // 5. Neem Kernel Seeds Serum 30ml
  {
    handle: 'serum-30ml-3nos',
    title: 'Neem Kernel Seeds Serum',
    subtitle: '30ml X 03 Nos',
    benefit: 'Follicle support pack of 3',
    price: 957,
    mrpPerUnit: 1710,
    imageUrl: '/serum.jpeg',
    category: 'serum',
    tags: ['30ml', '3nos', 'bundle'],
    description: 'Clinical strength hair follicle support in a wholesale pack of 3.',
    howToUse: ['Apply to scalp nightly.', 'Massage gently.'],
    ingredients: [{ name: 'Ginseng Root', benefit: 'Scalp stimulation' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'serum-30ml-6nos',
    title: 'Neem Kernel Seeds Serum',
    subtitle: '30ml X 06 Nos',
    benefit: 'Follicle support pack of 6',
    price: 1854,
    mrpPerUnit: 3420,
    imageUrl: '/serum.jpeg',
    category: 'serum',
    tags: ['30ml', '6nos', 'bundle'],
    description: 'Clinical strength hair follicle support in a wholesale pack of 6.',
    howToUse: ['Apply to scalp nightly.', 'Massage gently.'],
    ingredients: [{ name: 'Ginseng Root', benefit: 'Scalp stimulation' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'serum-30ml-12nos',
    title: 'Neem Kernel Seeds Serum',
    subtitle: '30ml X 12 Nos',
    benefit: 'Follicle support pack of 12',
    price: 3600,
    mrpPerUnit: 6840,
    imageUrl: '/serum.jpeg',
    category: 'serum',
    tags: ['30ml', '12nos', 'bundle'],
    description: 'Clinical strength hair follicle support in a wholesale pack of 12.',
    howToUse: ['Apply to scalp nightly.', 'Massage gently.'],
    ingredients: [{ name: 'Ginseng Root', benefit: 'Scalp stimulation' }],
    moq: 1,
    isActive: true,
  },

  // 6. Hair Care Kit
  {
    handle: 'hair-care-kit-3nos',
    title: 'Neem Seed Kernel Hair Care Kit',
    subtitle: 'Kit X 03 Nos',
    benefit: 'Complete starter regimen pack of 3',
    price: 1257,
    mrpPerUnit: 2250,
    imageUrl: '/kit.png',
    category: 'kit',
    tags: ['kit', '3nos', 'bundle'],
    description: 'Complete hair care combo with shampoo, conditioner, and serum. Pack of 3.',
    howToUse: ['Use as complete regimen.'],
    ingredients: [{ name: 'Neem Extract', benefit: 'Scalp health' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'hair-care-kit-6nos',
    title: 'Neem Seed Kernel Hair Care Kit',
    subtitle: 'Kit X 06 Nos',
    benefit: 'Complete starter regimen pack of 6',
    price: 2442,
    mrpPerUnit: 4500,
    imageUrl: '/kit.png',
    category: 'kit',
    tags: ['kit', '6nos', 'bundle'],
    description: 'Complete hair care combo with shampoo, conditioner, and serum. Pack of 6.',
    howToUse: ['Use as complete regimen.'],
    ingredients: [{ name: 'Neem Extract', benefit: 'Scalp health' }],
    moq: 1,
    isActive: true,
  },
  {
    handle: 'hair-care-kit-12nos',
    title: 'Neem Seed Kernel Hair Care Kit',
    subtitle: 'Kit X 12 Nos',
    benefit: 'Complete starter regimen pack of 12',
    price: 4740,
    mrpPerUnit: 9000,
    imageUrl: '/kit.png',
    category: 'kit',
    tags: ['kit', '12nos', 'bundle'],
    description: 'Complete hair care combo with shampoo, conditioner, and serum. Pack of 12.',
    howToUse: ['Use as complete regimen.'],
    ingredients: [{ name: 'Neem Extract', benefit: 'Scalp health' }],
    moq: 1,
    isActive: true,
  }
];

async function seedActualProducts() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB for ACTUAL Imerbela Bundle seeding');

    // Clear everything first to reset to the bundle-only catalog
    await Product.deleteMany({});
    console.log('🗑️  Cleared old unit-based products');
    
    for (const p of products) {
      await Product.create(p);
    }

    console.log('✅ Bundle-based Imerbela products seeded successfully');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seedActualProducts();
